# -*- coding: utf-8 -*-
"""Aula 20/05- app de orçamento streamlit

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AoWfIP-W3LayllZrrQjnhC2jbdL2il2Y
"""

import streamlit as st

st.title("Orçamento de Montagem de Computador")

valor = st.number_input(
    'Digite o valor disponível para a montagem do computador: ',
    min_value=0.0
)

st.write('Digite o valor de cada peça do computador:')

usuario_1 = st.number_input('Placa mãe: ', min_value=0.0)
usuario_2 = st.number_input('Memória RAM: ', min_value=0.0)
usuario_3 = st.number_input('Processador: ', min_value=0.0)
usuario_4 = st.number_input('Placa de vídeo: ', min_value=0.0)
usuario_5 = st.number_input('Armazenamento: ', min_value=0.0)
usuario_6 = st.number_input('Fonte de alimentação: ', min_value=0.0)
usuario_7 = st.number_input('Gabinete: ', min_value=0.0)
usuario_8 = st.number_input('Refrigerador: ', min_value=0.0)
usuario_9 = st.number_input('Monitor: ', min_value=0.0)
usuario_10 = st.number_input('Teclado e mouse: ', min_value=0.0)
usuario_11 = st.number_input('Sistema operacional: ', min_value=0.0)
usuario_12 = st.number_input('Periféricos: ', min_value=0.0)

if st.button('Calcular orçamento'):

    soma = (
        usuario_1 + usuario_2 + usuario_3 + usuario_4 +
        usuario_5 + usuario_6 + usuario_7 + usuario_8 +
        usuario_9 + usuario_10 + usuario_11 + usuario_12
    )

    st.write(f'\nO valor total para a montagem é: {soma}')

    if valor >= soma:
        restante = valor - soma
        st.success('Sua compra poderá ser realizada!')
        st.write(f'Agora, o valor disponível será: {restante}')

    else:
        st.error('Saldo insuficiente!')